[package]
name = "buzzcode-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[build-dependencies]
tauri-build = { version = "2.5", features = [] }

[dependencies]
tauri = { version = "2.10", features = [] }

[features]
custom-protocol = ["tauri/custom-protocol"]
